

about :

  name : wWebUriFundamentals
  description : Collection of routines to operate web URIs ( URLs ) in the reliable and consistent way. Module WebUri extends Uri module to handle host and port parts of URI in a way appropriate for world wide web resources. This module leverages parsing, joining, extracting, normalizing, nativizing, resolving paths. Use the module to get uniform experience from playing with paths on different platforms.
  version : 0.3.15
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wWebUriFundamentals.git
  bugs : https://github.com/Wandalen/wWebUriFundamentals/issues

build :

  debug.raw.export :
    exportDirPath : path::out.debug
    criterion :
      default : 1
      debug : 1
      raw : 1
      export : 1
      tar : 0
    steps :
      # - build::.debug.raw
      - step::export

  release.compiled.export :
    exportDirPath : path::out.release
    criterion :
      debug : 0
      raw : 0
      export : 1
      tar : 0
    steps :
      - build::release.compiled
      - step::export

  export.all :
    steps :
      - build::debug.raw.export
      - build::release.compiled.export

